# Generated by Django 4.2.7 on 2025-11-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
