# Generated by Django 4.2.7 on 2025-11-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0002_trabajador_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='apellido',
            field=models.CharField(default='Sin datos', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='nombre',
            field=models.CharField(default='Sin datos', max_length=100),
            preserve_default=False,
        ),
    ]
