# Generated by Django 4.2.7 on 2025-11-19 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del cliente', max_length=200, verbose_name='Nombre Completo')),
                ('cedula', models.CharField(help_text='Número de identificación único', max_length=20, unique=True, verbose_name='Cédula/DNI')),
                ('correo', models.EmailField(blank=True, help_text='Email del cliente (opcional)', max_length=254, null=True, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(help_text='Número de teléfono del cliente', max_length=20, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, help_text='Dirección física del cliente (opcional)', verbose_name='Dirección')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultima_compra', models.DateTimeField(blank=True, null=True, verbose_name='Última Compra')),
                ('total_compras', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto total acumulado en compras', max_digits=12, verbose_name='Total en Compras')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el cliente está activo en el sistema', verbose_name='Cliente Activo')),
                ('notas', models.TextField(blank=True, help_text='Observaciones o notas sobre el cliente', verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['cedula'], name='clientes_cl_cedula_4c3f46_idx'), models.Index(fields=['nombre'], name='clientes_cl_nombre_c231de_idx'), models.Index(fields=['-fecha_registro'], name='clientes_cl_fecha_r_483ee3_idx')],
            },
        ),
    ]
